- name: Prompt
  ansible.builtin.pause:
    prompt: Please enter the target host IP
  register: target_host

- name: Add target hosts to dynamically created hosts group
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups: dynamically_created_hosts
  with_items: "{{ target_host.user_input | split(',') }}"

- name: Get hostvars
  ansible.builtin.debug:
    var: hostvars
  delegate_to: localhost
