#SPDX-License-Identifier: MIT-0
---
# handlers file for rpi4_coreos
- name: Remove templated files
  ansible.builtin.file:
    path: "{{ role_path }}/files/templated/{{ item }}"
    state: absent
  loop:
    - config.bu
    - config.ign
    - provision_image.sh
  listen: "cleanup_handler"
  delegate_to: localhost

- name: Reboot remote and wait for it to restart
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  delegate_to: picoreos_hosts
  listen: "reboot_handler"
  tags: [reboot, rpi4_reboot]
