  # use FCCT to transpile config.bu to config.ign
- name: Transpile to config.ign
  ansible.builtin.import_tasks: provision/01_transpile.yaml
  # run script to install coreos to microsd card
  # if coreos-installer is installed (fedora only)
- name: Install to microsd if coreos-installer is present
  ansible.builtin.include_tasks:
    file: provision/02_01_image_ssd.yaml
    apply:
      become: true
      become_method: ansible.builtin.sudo
  when: "'coreos-installer' in local_pkgs.ansible_facts.packages"
  # install coreos to microsd card using container
  # (other distros ie when coreos-installer is not installed)
  # (uses privilged podman container)
- name: Install to microsd if coreos-installer is not present
  ansible.builtin.include_tasks:
    file: provision/02_02_image_ssd.yaml
    apply:
      become: true
      become_method: ansible.builtin.sudo
  when: "'coreos-installer' not in local_pkgs.ansible_facts.packages"
  # install firmware to microsd card
- name: Install firmware
  ansible.builtin.include_tasks:
    file: provision/03_install_firmware.yaml
    apply:
      become: true
      become_method: ansible.builtin.sudo
